services:
  tools:
    image: nvidia/cuda:12.1.0-devel-ubuntu22.04
    container_name: ai_influencer_tools
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DEBIAN_FRONTEND=noninteractive
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    working_dir: /workspace
    volumes:
      - ../data:/workspace/data
      - ../scripts:/workspace/scripts
      - ../scripts:/scripts
    command: >
      bash -lc "
      apt-get update &&
      apt-get install -y python3 python3-pip git &&
      pip3 install --no-cache-dir -r /workspace/scripts/requirements.txt &&
      python3 /workspace/scripts/bootstrap_models.py &&
      tail -f /dev/null
      "

  comfyui:
    build:
      context: ..
      dockerfile: docker/comfyui.Dockerfile
    container_name: comfyui_local
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports: ["8188:8188"]
    volumes:
      - ../models:/opt/ComfyUI/models
      - ../workflows/comfyui:/opt/ComfyUI/user/default
      - ../data:/data


  kohya:
    build:
      context: ..
      dockerfile: docker/kohya.Dockerfile
    container_name: kohya_local
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../data:/workspace/data
      - ../models:/workspace/models
      - ../scripts:/workspace/scripts
    working_dir: /workspace
    command: bash -lc "tail -f /dev/null"

  webapp:
    image: python:3.11-slim
    container_name: ai_influencer_webapp
    depends_on:
      - tools
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_APP_TITLE=AI Influencer Control Hub
    working_dir: /workspace
    volumes:
      - ../../:/workspace
    command: >
      bash -lc "
      apt-get update && \
      apt-get install -y --no-install-recommends build-essential python3-dev && \
      rm -rf /var/lib/apt/lists/* && \
      pip install --no-cache-dir -r ai_influencer/webapp/requirements.txt && \
      uvicorn ai_influencer.webapp.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"

  n8n:
    build:
      context: ..
      dockerfile: docker/n8n.Dockerfile
    container_name: n8n_local
    depends_on:
      - tools
      - kohya
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-admin}
      - N8N_USER_FOLDER=/data
      - N8N_IMPORT_EXPORT_DIR=/imports
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://localhost:5678/}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/data
      - ../n8n:/imports
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  n8n_data:
